package com.cmp.fragalyzer.types;

public enum KitType {
	KIT_TYPE_AT, 
	KIT_TYPE_SMGASSAULT, 
	KIT_TYPE_RIFLEASSAULT, 
	KIT_TYPE_NCO, 
	KIT_TYPE_ENGINEER, 
	KIT_TYPE_PILOT, 
	KIT_TYPE_SAPPER, 
	KIT_TYPE_TANKER, 
	KIT_TYPE_MEDIC, 
	KIT_TYPE_SNIPER,
	KIT_TYPE_MORTAR, 
	KIT_TYPE_LMG, 
	KIT_TYPE_HMG, 
	KIT_TYPE_SCOUT, 
	KIT_TYPE_MAGIC, 
	KIT_TYPE_AMMO, 
	NUM_KIT_TYPES,
	UNKNOWN
}
